version: "3"
services:

  django:
    build:
      context: .
      dockerfile: ./Dockerfile_django
    volumes:
      - ./app/server/static:/app/server/static
    command: ["./tools/dev-django.sh", "0.0.0.0:8000"]
    environment:
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "${PASSWORD}"
      ADMIN_EMAIL: "admin@example.com"
      DATABASE_URL: "postgres://doccano:doccano@postgres:5432/doccano?sslmode=disable"
      ALLOW_SIGNUP: "False" 
    ports:
      - 80:8000

  webpack:
    build: 
      context: .
      dockerfile: ./Dockerfile_webpack
    volumes:
      - ./app/server/static/webpack-stats.json:/app/server/static/webpack-stats.json
    environment:
      WEBPACK_HOST: "0.0.0.0"
      WEBPACK_PORT: "8080"
      WEBPACK_POLL_MILLIS: "1000"
    ports:
      - 8080:8080

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: "doccano"
      POSTGRES_PASSWORD: "doccano"
      POSTGRES_DB: "doccano"
    ports:
      - 5432:5432

volumes:
  node_modules:
  venv:
